model_list:
  - model_name: "stable-diffusion"
    litellm_params:
      model: "comfyui/stable-diffusion"
      checkpoint: "stable-diffusion-v1-5-pruned.safetensors"
      api_base: "127.0.0.1:8188"

litellm_settings:
  custom_provider_map:
  - {"provider": "comfyui", "custom_handler": comfyui_handler.comfyui}

general_settings: 
  master_key: sk-1234
